# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CGsDoGbA0xXPgBuRAQxt24iKV7Kb4WxF
"""

pip install streamlit

import pandas as pd
import streamlit as st
from scipy.stats import ttest_ind
import altair as alt

# Загрузка данных
uploaded_file = st.file_uploader("Выберите файл CSV", type="csv")
if uploaded_file is not None:
    data = pd.read_csv(uploaded_file)

    # Вывод данных
    st.write("Данные:")
    st.write(data)

    # Задание параметров
    age = st.slider("Выберите возраст", min_value=18, max_value=65, value=35, step=1)
    work_days = st.slider("Выберите количество пропущенных рабочих дней", min_value=0, max_value=10, value=2, step=1)

    # Сформулирование гипотез
    H0 = "Среднее количество пропущенных рабочих дней сотрудниками старше {} лет и моложе {} лет одинаково".format(age, age)
    H1 = "Среднее количество пропущенных рабочих дней сотрудниками старше {} лет больше, чем у молодых сотрудников".format(age)

    # Выполнение проверки гипотез
    old_employees_work_days = data[data['age'] > age]['work_days']
    young_employees_work_days = data[data['age'] <= age]['work_days']
    t_stat, p_value = ttest_ind(old_employees_work_days, young_employees_work_days, equal_var=False)

    # Отображение результатов
    st.write("Результат проверки гипотез:")
    if p_value < 0.05:
        st.write(f"Гипотеза: Отвергаем H0, принимаем H1")
    else:
        st.write(f"Гипотеза: Не удалось отвергнуть H0")

    # Отображение графиков
    st.write("Графики распределений:")
    chart = alt.Chart(data).mark_bar().encode(
        x=alt.X('work_days', bin=True),
        y='count()',
        color=alt.condition(
            alt.datum.age > age,
            alt.value('orange'), alt.value('blue')
        )
    ).properties(
        width=600,
        height=400
    )
    st.altair_chart(chart)